### ISSUE TITLE
(packet?) Can't run terraform plan/apply

### ISSUE THREAD

**Issue by DGollings** [kinvolk/lokomotive-kubernetes#158]
On master (2512344), can't run anything terraform related really. I disabled all modules except for worker/controller, didn't help. Not much more I can think of to help fix this right now.

Following error message:
```
Error: could not generate output checksum: lstat .terraform/modules/controller.bootkube/resources/charts/calico: no such file or directory



Error: could not generate output checksum: lstat .terraform/modules/controller.bootkube/resources/bootstrap-manifests: no such file or directory



Error: could not generate output checksum: lstat .terraform/modules/controller.bootkube/resources/charts/kubernetes: no such file or directory

```

**Comment by invidian** [comment]
@DGollings thanks for reporting. maybe you can try removing `. terraform` directory and running `terraform init` again?

**Comment by DGollings** [comment]
Already tried that in order to get back to an older commit, think I had to remove tfstate as well (on s3). Will try later and let you know, thanks

**Comment by invidian** [comment]
@DGollings I checked it and there is indeed an issue when updating to 2512344, I was able to reproduce it.

The problem is that `template_dir` resource from `bootkube` module holds the reference to the old path to `bootkube` module generated by Terraform via `source_dir` parameter. Then when planning, it tries to stat it and returns an error if the path does not exist anymore.

I'm not sure if that's the right approach yet, but it seems, that removing those resources from state and letting Terraform recreate them solves the issue:
```
$ terraform state list  | grep template_dir | grep bootkube
module.controller.module.bootkube.template_dir.bootstrap-manifests
module.controller.module.bootkube.template_dir.calico[0]
module.controller.module.bootkube.template_dir.kubelet
module.controller.module.bootkube.template_dir.kubernetes
$ terraform state rm module.controller.module.bootkube.template_dir.bootstrap-manifests module.controller.module.bootkube.template_dir.calico[0] module.controller.module.bootkube.template_dir.kubelet module.controller.module.bootkube.template_dir.kubernetes
Removed module.controller.module.bootkube.template_dir.kubernetes
Removed module.controller.module.bootkube.template_dir.kubelet
Removed module.controller.module.bootkube.template_dir.bootstrap-manifests
Removed module.controller.module.bootkube.template_dir.calico[0]
Successfully removed 4 resource instance(s).
```

You can try this out.

Another workaround would be to create a symlink to satisfy `terraform_dir`:
```
ln -s ./controller/bootkube .terraform/modules/controller.bootkube
```

Then run `terraform apply`, so `template_dir` resources can update their path.

**Comment by DGollings** [comment]
Just now deleted .terraform and the (remote) terraform.tfstate and it 'compiles' again, seems to be a temporary bug/feature due to a large? refactor.

Thanks, closing this issue
